version: '3.8'

services:
  intent-classifier:
    build:
      context: ..  # Build from parent directory to access all files
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/onnx-intent-classifier
      - TOKENIZERS_PARALLELISM=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"